### ISSUE TITLE
Inverted comments

### ISSUE THREAD

**Issue by busstoptaktik** [NordicGeodesy/NordicTransformations#10]
In `resources/NKG` the comments:

    # ITRF2008 -> NKG_ETRF00
    # ITRF2014 -> NKG_ETRF00

appear to say the opposite of the actually implemented transformations

(Reported by Lars Stenseng, DTU space)

**Comment by kbevers** [comment]
Correct. Please fix :-)

**Comment by kbevers** [comment]
Thanks!

**Comment by busstoptaktik** [comment]
jurvælkåm :-)
