### ISSUE TITLE
Time span reverse in PROJ 6.0.0

### ISSUE THREAD

**Issue by VladimirEI** [NordicGeodesy/NordicTransformations#14]
Hi,
Has the time span reverse from PROJ ver. 6.0.0 [(see here)](https://proj.org/usage/differences.html#changes-to-deformation) been taken into account in the NKG transformation pipelines?

Practically speaking, if I take PROJ docker [container](https://hub.docker.com/r/osgeo/proj/tags) from their docker hub, will the time transformations still be in the correct directions?

**Comment by kbevers** [comment]
As per a0551aa573d99a48d62be4d55229afd71c4179b4, yes.

**Comment by VladimirEI** [comment]
Thanks. It would be nice to have a CHANGELOG file where it is written to what PROJ version current version is compliant to, since the data in repository are tightly coupled with PROJ.

**Comment by kbevers** [comment]
The data here is kept up to date with recent developments of PROJ. That is the benefit of having the same person maintain both distributions :-) The commit log is the changelog: https://github.com/NordicGeodesy/NordicTransformations/commits/master.

If you use the most recent version of PROJ and proj-datumgrid-europe you will be sure to get a matching set of software and parameter files.
