### ISSUE TITLE
Broken in newer versions of PROJ (?)

### ISSUE THREAD

**Issue by GEO-NPA** [NordicGeodesy/NordicTransformations#19]
Seems like the transformations has broken sometime between PROJ 6.0.0 and the 8.2.1 release.
I couldn't get it to work on Python 3.10, PROJ 8.2.1 (with GDAL 3.4.1): 
`PROJ: proj_create: Error 1025 (Invalid PROJ string syntax): pipeline: Pipeline: Bad step definition: init=DK:S34S (Invalid PROJ string syntax)`
However when downgrading to Python 3.6, PROJ 6.0.0  (with GDAL 3.0.4), the transformations work.

My guess would be the structure and syntax of the PROJ file(s) has changed once again, rendering old ones broken.

**Comment by kbevers** [comment]
Cannot replicate with version 9.0.0:

```
C:\> proj
Rel. 9.0.0, March 1st, 2022
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]

C:\> projsync --source-id dk_sdfe
Downloading from https://cdn.proj.org into C:\Users\b012349\AppData\Local/proj
https://cdn.proj.org/dk_sdfe_dvr90.tif already downloaded.
Total size to download: 9 MB
Downloading https://cdn.proj.org/dk_sdfe_README.txt... (1 / 13)
Downloading https://cdn.proj.org/DK... (2 / 13)
Downloading https://cdn.proj.org/FO... (3 / 13)
Downloading https://cdn.proj.org/dk_sdfe_DK_bornholm.pol... (4 / 13)
Downloading https://cdn.proj.org/dk_sdfe_DK_bridges.pol... (5 / 13)
Downloading https://cdn.proj.org/dk_sdfe_DK_general.pol... (6 / 13)
Downloading https://cdn.proj.org/dk_sdfe_DK_jutland.pol... (7 / 13)
Downloading https://cdn.proj.org/dk_sdfe_DK_zealand.pol... (8 / 13)
Downloading https://cdn.proj.org/dk_sdfe_FO_fk89.pol... (9 / 13)
Downloading https://cdn.proj.org/dk_sdfe_dnn.tif... (10 / 13)
Downloading https://cdn.proj.org/dk_sdfe_fvr09.tif... (11 / 13)
Downloading https://cdn.proj.org/dk_sdfe_gvr2000.tif... (12 / 13)
Downloading https://cdn.proj.org/dk_sdfe_gvr2016.tif... (13 / 13)

C:\>echo 12.5 55.75 0 0 | cct +init=DK:S34S
   76596.6512    148606.2800      -34.0953        0.0000
```

I'm closing this until further proof of things not working are presented. It's quite likely to be an issue with the resource files missing. They can be installed with `projsync` as demonstrated above.

**Comment by GEO-NPA** [comment]
Problem was with pyproj and not NordicTransformations 😊
